try{
    console.log("error check");
}catch (e){
    console.log(e);
}